### ISSUE TITLE
Add Alisa to mild.blue

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/about#102]
Viz treba PR https://github.com/mild-blue/about/issues/95 udelat podobne.

**Comment by notsousual** [comment]
https://github.com/mild-blue/about/commit/23ff025e9a5ba8726874f66dc0a2f83d09bb25c7
branch 'alisa' https://github.com/mild-blue/about/tree/alisa
@kubantjan @misslecter

**Comment by kubantjan** [comment]
@notsousual udělej prosím rovnou pull request z tý branche at se to líp komentuje

**Comment by notsousual** [comment]
uz je :) @kubantjan

**Comment by notsousual** [comment]
https://github.com/mild-blue/about/pull/104

**Comment by kubantjan** [comment]
Jeste pak propojuj prosim issue a PR (ted jsem to udelal, pak se magicky stane, ze kdyz se zavre PR tak se zavre issue a to propojeni je hezky videt :)

**Comment by notsousual** [comment]
@kubantjan upd
