### ISSUE TITLE
Text overlapping on the main mild.blue page while resizing (-on non-typical window sizes)

### ISSUE THREAD

**Issue by notsousual** [mild-blue/about#105]
E.g 967 x 533
<img width="555" alt="Screenshot 2022-04-01 at 12 50 06" src="https://user-images.githubusercontent.com/47920627/161395892-a9b5d60e-d9e8-4890-b9d6-a45cdccfa471.png">
.

**Comment by StepanKarel** [comment]
Děje se taky toto: zmenšení okna -> klik na cokoli v menu -> nezle scrollovat jinam dokud nerefreshnu stránku

**Comment by bielovico** [comment]
Původní issue nešlo zreplikovat, na druhou issue novou kartičku.
