### ISSUE TITLE
We stand with ukraine dont show flag in desktop version

### ISSUE THREAD

**Issue by Skreta90** [mild-blue/about#174]
desktop
![UA je nevycentrované](https://user-images.githubusercontent.com/120102053/207882757-de3cdbdb-19fa-43ce-b63f-aa0c35ba8ab9.png)

mobile android
![319401901_542648811063336_957640620101871814_n](https://user-images.githubusercontent.com/120102053/207883394-0d9d3d68-bb06-4b07-bb44-3d037f7f607c.jpg)

**Comment by bielovico** [comment]
Works in Firefox 108.0.1

**Comment by tomaskourim** [comment]
Version 108.0.5359.125 (Official Build) (64-bit) nefunguje
