### ISSUE TITLE
Broken project table in mobile version

### ISSUE THREAD

**Issue by Skreta90** [mild-blue/about#175]
mild.blue na mobilu (android)

tabulka projetků - zmačknu šipku na přepnutí do jiného projetku -> změním jazyk -> zmačknu šipku na přepnutí do jiného projektu (někdy musím víckrát) -> v tabulce projektů se ukazuje více projektů najednou

![319082327_5916352671758995_8461340460518045353_n](https://user-images.githubusercontent.com/120102053/207884475-1038b321-b61a-4484-88c4-a216c066c95a.jpg)
![320011056_1132528947467650_364026519532267616_n](https://user-images.githubusercontent.com/120102053/207884449-9167cd03-b37d-4534-b9ab-a29311cd6ba2.jpg)

**Comment by bielovico** [comment]
Maybe connected to https://github.com/mild-blue/mild.blue/issues/104

**Comment by bielovico** [comment]
Working on this in https://github.com/mild-blue/mild.blue/issues/104
