### ISSUE TITLE
Button "demo" on datavid.org

### ISSUE THREAD

**Issue by StepanKarel** [mild-blue/about#176]
https://datavid.org

tlačítko demo s odkazem na stránku hází tohle: 
Web datavid.demo.mild.blue používá nepodporovaný protokol.

ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Nepodporovaný protokol

**Comment by bielovico** [comment]
Nedokážem replikovať.

**Comment by tomaskourim** [comment]
mne toto 
![image](https://user-images.githubusercontent.com/50045455/210185627-f47d2295-cc4e-458f-b94e-e3fd034fed5a.png)

**Comment by bielovico** [comment]
Ok, teraz to vidím aj ja (nie som si istý, či som to vlastne správne reprodukoval). Raisnem ďalej.

**Comment by bielovico** [comment]
Lukáš a Honza Skála vyriešili, pridaním CNAME (asi do Cloudflare? 🤷 ), viď konverzácia v chate https://chat.google.com/room/AAAAH0UWzK0/H6jaId8Dcy0
