### ISSUE TITLE
Readme.md - broken link to Onepager GitHub repository

### ISSUE THREAD

**Issue by kuchapav** [mild-blue/about#96]
neni priorita, protoze onepage se nepouzivat

**Comment by kubantjan** [comment]
@kuchapav  tohle nechapu, ten link mi funguje?

**Comment by kuchapav** [comment]
Mi to dává 404 když na to kliknu.

![image](https://user-images.githubusercontent.com/6392761/165151831-e58d2e74-d7c6-4e45-8636-df2ef8726ef2.png)

**Comment by bielovico** [comment]
V Readme.md je spravny link na onepager
